### ISSUE TITLE
Options for OIDC authenticate call not documented

### ISSUE THREAD

**Issue by BigBallard** [passport/discuss#57]
I am having a hard time determining what the possible options are for the *passport.authenticate()* call. What I have seen so far from other posts are specifying redirect for success and failure but nothing else. Also, are those two options relative paths only?

**Comment by mattpen** [comment]
I'm having the same trouble.  Is there any reference documentation for `passport.authenticate` available?

**Comment by mattpen** [comment]
Maybe this is it? https://github.com/jwalton/passport-api-docs

**Comment by BigBallard** [comment]
Looks like it may be it!
